export const createComponentHelp = (args) => {
    return [
        '',
        '<font color="cyan" bold>Usage:</font>',
        '<tab/><font color="green">nd create:component</font> <font color="gray"><componentName> [--feature <featureName>]</font>',
        '',
        '<font color="cyan" bold>Examples:</font>',
        '<tab/><font color="green">nd create:component button</font>',
        '<tab/><font color="green">nd create:component user-card</font>',
        '<tab/><font color="green">nd create:component login-form --feature auth</font>',
        '',
        '<font color="gray">Run with --params for more details</font>',
        ...(args?.includes('--params') ? [
            '',
            '<font color="cyan" bold>Parameters:</font>',
            '',
            '<tab/><font color="green">componentName</font>',
            '<tab repeat="2"/><font color="gray">Type    : string</font>',
            '<tab repeat="2"/><font color="gray">Required: yes</font>',
            '<tab repeat="2"/><font color="gray">Example : button, user-card, login-form</font>',
            '<tab repeat="2"/><font color="gray">Note    : kebab-case recommended</font>',
            '',
            '<tab/><font color="green">--feature</font>',
            '<tab repeat="2"/><font color="gray">Type    : string</font>',
            '<tab repeat="2"/><font color="gray">Required: no</font>',
            '<tab repeat="2"/><font color="gray">Note    : generate inside a feature folder</font>',
            '<tab repeat="2"/><font color="gray">Example : --feature auth</font>',
            '',
            '<font color="cyan" bold>Generates (default):</font>',
            '<tab/><font color="gray">src/components/componentName/ComponentName.js</font>',
            '<tab/><font color="gray">src/components/componentName/componentName.css</font>',
            '',
            '<font color="cyan" bold>Generates (--feature auth):</font>',
            '<tab/><font color="gray">src/features/auth/components/componentName/ComponentName.js</font>',
            '<tab/><font color="gray">src/features/auth/components/componentName/componentName.css</font>',
        ] : []),
    ];
};