export const createServiceHelp = (args) => {
    return [
        '',
        '<font color="cyan" bold>Usage:</font>',
        '<tab/><font color="green">nd create:service</font> <font color="gray"><serviceName> [--feature <featureName>]</font>',
        '',
        '<font color="cyan" bold>Examples:</font>',
        '<tab/><font color="green">nd create:service auth</font>',
        '<tab/><font color="green">nd create:service user-profile</font>',
        '<tab/><font color="green">nd create:service product --feature shop</font>',
        '',
        '<font color="gray">Run with --params for more details</font>',
        ...(args?.includes('--params') ? [
            '',
            '<font color="cyan" bold>Parameters:</font>',
            '',
            '<tab/><font color="green">serviceName</font>',
            '<tab repeat="2"/><font color="gray">Type    : string</font>',
            '<tab repeat="2"/><font color="gray">Required: yes</font>',
            '<tab repeat="2"/><font color="gray">Example : auth, user-profile, product</font>',
            '<tab repeat="2"/><font color="gray">Note    : kebab-case recommended</font>',
            '',
            '<tab/><font color="green">--feature</font>',
            '<tab repeat="2"/><font color="gray">Type    : string</font>',
            '<tab repeat="2"/><font color="gray">Required: no</font>',
            '<tab repeat="2"/><font color="gray">Note    : generate inside a feature folder</font>',
            '<tab repeat="2"/><font color="gray">Example : --feature shop</font>',
            '',
            '<font color="cyan" bold>Generates (default):</font>',
            '<tab/><font color="gray">src/services/ServiceName.js</font>',
            '',
            '<font color="cyan" bold>Generates (--feature shop):</font>',
            '<tab/><font color="gray">src/features/shop/services/ServiceName.js</font>',
        ] : []),
    ];
};