export const createHelp = (args) => {
    return [
        '',
        '<font color="cyan" bold>Usage:</font>',
        '<tab/><font color="green">nd create</font> <font color="gray"><ProjectName> [--template <name|url>] [--feature]</font>',
        '',
        '<font color="cyan" bold>Examples:</font>',
        '<tab/><font color="green">nd create MyApp</font>',
        '<tab/><font color="green">nd create MyApp --feature</font>',
        '<tab/><font color="green">nd create MyApp --template saas</font>',
        '<tab/><font color="green">nd create MyApp --template saas --feature</font>',
        '<tab/><font color="green">nd create MyApp --template=https://github.com/my/template</font>',
        '',
        '<font color="gray">Run with --params for more details</font>',
        ...(args?.includes('--params') ? [
            '',
            '<font color="cyan" bold>Parameters:</font>',
            '',
            '<tab/><font color="green">ProjectName</font>',
            '<tab repeat="2"/><font color="gray">Type    : string</font>',
            '<tab repeat="2"/><font color="gray">Required: yes</font>',
            '<tab repeat="2"/><font color="gray">Example : MyApp, TodoApp, Dashboard</font>',
            '<tab repeat="2"/><font color="gray">Note    : PascalCase recommended</font>',
            '',
            '<tab/><font color="green">--template</font>',
            '<tab repeat="2"/><font color="gray">Type    : string</font>',
            '<tab repeat="2"/><font color="gray">Required: no</font>',
            '<tab repeat="2"/><font color="gray">Default : official NativeDocument template</font>',
            '<tab repeat="2"/><font color="gray">Value   : registered name or direct URL</font>',
            '',
            '<tab/><font color="green">--feature</font>',
            '<tab repeat="2"/><font color="gray">Type    : boolean</font>',
            '<tab repeat="2"/><font color="gray">Required: no</font>',
            '<tab repeat="2"/><font color="gray">Default : false</font>',
            '<tab repeat="2"/><font color="gray">Note    : enables feature-based architecture</font>',
        ] : []),
    ];
};